package randomwalkgraph;

import java.util.List;
import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author andrewtaylor
 */
public class RandomWalkMainPanel extends javax.swing.JPanel {

    private List<Integer> coordinates;
    private Random random;
    private PascalsTriangle pascalsTriangle;
    
    /**
     * Creates new form RandomWalkMainPanel
     */
    public RandomWalkMainPanel() {
        initComponents();
        coordinates = new ArrayList<>();
        coordinates.add(0);
        random = new Random();
        pascalsTriangle = new PascalsTriangle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stepButton = new javax.swing.JButton();
        graphPanel = new RandomWalkGraphPanel();
        jLabel1 = new javax.swing.JLabel();
        numStepsTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        distanceTravelledTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        probabilityTextField = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1000, 1000));

        stepButton.setText("Step");
        stepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );

        jLabel1.setText("Number of steps");

        jLabel2.setText("Distance travelled");

        jLabel3.setText("Probability");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(stepButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(numStepsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(distanceTravelledTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(probabilityTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stepButton)
                    .addComponent(jLabel1)
                    .addComponent(numStepsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(distanceTravelledTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(probabilityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(graphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void stepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepButtonActionPerformed
        int step = random.nextBoolean() ? 1 : -1;
        int distance = coordinates.get(coordinates.size() - 1) + step;
        coordinates.add(distance);
        
        int numSteps = coordinates.size() - 1;
             
        pascalsTriangle.generateRow();
        double prob = pascalsTriangle.getProbability(numSteps, distance);
        
        numStepsTextField.setText(String.valueOf(numSteps));
        distanceTravelledTextField.setText(String.valueOf(distance));
        probabilityTextField.setText(String.valueOf(prob));
       
        ((RandomWalkGraphPanel) graphPanel).update(coordinates);
    }//GEN-LAST:event_stepButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField distanceTravelledTextField;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField numStepsTextField;
    private javax.swing.JTextField probabilityTextField;
    private javax.swing.JButton stepButton;
    // End of variables declaration//GEN-END:variables
}
